
export const RESET = 'RESET';
export const LOGOUT = 'LOGOUT';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const TOKEN = 'TOKEN';
export const TOKEN_FAILED = 'TOKEN_FAILED';

export const FECTH_LOYALTY = 'FECTH_LOYALTY';
export const FECTH_LOYALTY_FAILED = 'FECTH_LOYALTY_FAILED';
export const FECTH_LOYALTY_RECEIVED = 'FECTH_LOYALTY_RECEIVED';

export const FECTH_PRODUCT = 'FECTH_PRODUCT';
export const FECTH_PRODUCT_RECEIVED = 'FECTH_PRODUCT_RECEIVED';
export const FECTH_PRODUCT_FAILED = 'FECTH_PRODUCT_FAILED';

export const REDEEM_PRODUCT = 'REDEEM_PRODUCT';
export const REDEEM_PRODUCT_RECEIVED = 'REDEEM_PRODUCT_RECEIVED';
export const REDEEM_PRODUCT_FAILED = 'REDEEM_PRODUCT_FAILED';

//notification related
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';


